### ISSUE TITLE
Cannot get this plugin to work

### ISSUE THREAD

**Issue by justpeanuts** [vthuongt/window-switcher-plus#1]
I copied the window-switcher-plus.py file into ~/.local/share/albert/org.albert.extension.python/modules/ directory.
Upon looking in the Python plugin options in Albert's preferences, the window switcher plus is shown as a plugin but the option is greyed out and there is also a greyed out x mark instead of the tick mark.
Albert version: 0.17.2

**Comment by VietTralala** [comment]
Hi, thanks for pointing out this bug. I haven't used this script for some time and from a quick glance it appears that albert has changed it's python plugin api slightly. So I need to make some small changes. Hopefully I will be able to find some time today and push the updates by tomorrow.

**Comment by VietTralala** [comment]
Should be fixed with the current [commit](https://github.com/vthuongt/window-switcher-plus/commit/0d33f1a6c06fc859110814849550cd7f31dbf7d9) 

Thus I will close the issue. Please reopen if it still doesn't work

**Comment by justpeanuts** [comment]
The plugin works flawlessly now. The priority given to the window switch action is also better in your plugin than the original default window switcher plugin. Thank you so much. You are awesome! :)
